services:
  postgres:
    container_name: rural-producers
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: main
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres

volumes:
  pgdata: